=== grafnu/udmi/schema/config.json
{
  "$udmi_version": "1.5.7",
  "title": "Config",
  "description": "The config block controls a device's intended behavior. [Config Documentation](../docs/messages/config.md)",
  "$section": "Messages",
  "type": "object",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "required": [
    "timestamp",
    "version"
  ],
  "properties": {
    "timestamp": {
      "description": "RFC 3339 UTC timestamp the configuration was generated",
      "type": "string",
      "format": "date-time",
      "examples": ["2019-01-17T14:02:29.364Z"]
    },
    "version": {
      "description": "Version of the UDMI schema",
      "type": "string"
    },
    "downgraded_from": {
      "description": "Original version of schema pre-downgrade",
      "type": "string"
    },
    "system": {
      "$ref": "file:config_system.json#"
    },
    "gateway": {
      "$ref": "file:config_gateway.json#"
    },
    "discovery": {
      "$ref": "file:config_discovery.json#"
    },
    "localnet": {
      "$ref": "file:config_localnet.json#"
    },
    "blobset": {
      "$ref": "file:config_blobset.json#"
    },
    "notifs": {
      "$ref": "config_notifs.json"
    },
    "pointset": {
      "$ref": "file:config_pointset.json#"
    }
  }
}

=== grafnu/udmi/validator/sequences/basic_notification/config_update.json
{
  "discovery" : {
    "families" : {
      "bacnet" : { },
      "vendor" : { }
    }
  },
  "localnet" : {
    "families" : {
      "bacnet" : { },
      "ether" : { },
      "ipv4" : { },
      "vendor" : { }
    }
  },
  "notifs" : {
    "notif_id" : { }
  },
  "pointset" : {
    "points" : {
      "filter_alarm_pressure_status" : {
        "ref" : "BV/11#present_value",
        "units" : "No-units"
      },
      "filter_differential_pressure_sensor" : {
        "ref" : "AV/12#present_value",
        "units" : "Degrees-Celsius"
      },
      "filter_differential_pressure_setpoint" : {
        "set_value" : 98,
        "units" : "Bars"
      }
    },
    "sample_rate_sec" : 300
  },
  "system" : {
    "metrics_rate_sec" : 10,
    "min_loglevel" : 100,
    "operation" : {
      "last_start" : "TIMESTAMP"
    },
    "testing" : {
      "sequence_name" : "basic_notification"
    }
  },
  "timestamp" : "TIMESTAMP",
  "version" : "@@@cloud udmi version###1.4.1"
}

=== grafnu/udmi/tests/sites/basic/devices/SNS-4/expected/generated_config.json
{
  "gateway": {
    "target": {
      "addr": "2",
      "family": "modbus",
      "network_id": "modbus_rtu_1"
    }
  },
  "pointset": {
    "sample_rate_sec": 30
  },
  "system": {
    "metrics_rate_sec": 10,
    "min_loglevel": 300,
    "operation": {}
  },
  "timestamp": "2020-05-01T13:39:07Z",
  "version": "1.5.3"
}

=== grafnu/udmi/validator/sequences/basic_notification/state_update.json
{
  "discovery" : {
    "families" : { }
  },
  "localnet" : {
    "families" : {
      "bacnet" : {
        "addr" : "27312"
      },
      "ether" : {
        "addr" : "9c:65:eb:bb:a7:7e"
      },
      "ipv4" : {
        "addr" : "10.5.48.84"
      },
      "vendor" : {
        "addr" : "28179023"
      }
    }
  },
  "pointset" : {
    "points" : {
      "filter_alarm_pressure_status" : {
        "units" : "No-units"
      },
      "filter_differential_pressure_sensor" : {
        "units" : "Degrees-Celsius"
      },
      "filter_differential_pressure_setpoint" : {
        "units" : "Bars",
        "value_state" : "applied"
      }
    }
  },
  "system" : {
    "hardware" : {
      "make" : "BOS",
      "model" : "pubber"
    },
    "last_config" : "TIMESTAMP",
    "operation" : {
      "last_start" : "TIMESTAMP",
      "mode" : "initial",
      "operational" : true,
      "restart_count" : 1
    },
    "serial_no" : "sequencer-13289",
    "software" : {
      "firmware" : "v1",
      "system" : "v1"
    },
    "status" : {
      "category" : "system.config.apply",
      "level" : 300,
      "message" : "success",
      "timestamp" : "TIMESTAMP"
    }
  },
  "timestamp" : "TIMESTAMP",
  "version" : "1.5.7"
}
