=== grafnu/udmi/schema/metadata.json
{
  "$udmi_version": "1.5.7",
  "title": "Metadata",
  "description": "[Metadata](../docs/specs/metadata.md) is a description about the device: a specification about how the device should be configured and expectations about what the device should be doing. Defined by `metadata.json`",
  "$section": "Site Model",
  "type": "object",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "additionalProperties": false,
  "required": [ 
    "timestamp",
    "version",
    "system"
  ],
  "properties": {
    "timestamp": {
      "description": "RFC 3339 timestamp UTC the data was generated",
      "type": "string",
      "format": "date-time",
      "examples": ["2019-01-17T14:02:29.364Z"]
    },
    "version": {
      "description": "Version of the UDMI schema for this file",
      "type": "string"
    },
    "upgraded_from": {
      "description": "Original version of the UDMI schema for this file",
      "type": "string"
    },
    "hash": {
      "description": "DEPRECATED",
      "type": "string",
      "pattern": "^[0-9a-z]{8}$"
    },
    "operation": {
      "description": "Used for model update operations (so not a model proper), e.g. DELETE or BIND operations",
      "$ref": "file:common.json#/definitions/operation"
    },
    "cloud": {
      "$ref": "file:model_cloud.json#",
      "$presentation": {
        "section": "cloud"
      }
    },
    "system": {
      "$ref": "file:model_system.json#",
      "$presentation": {
        "section": "system"
      }
    },
    "externals": {
      "$ref": "file:model_externals.json#"
    },
    "relationships": {
      "$ref": "file:model_relationships.json#"
    },
    "gateway": {
      "$ref": "file:model_gateway.json#",
      "$presentation": {
        "section": "gateway"
      }
    },
    "discovery": {
      "$ref": "file:model_discovery.json#"
    },
    "localnet": {
      "$ref": "file:model_localnet.json#",
      "$presentation": {
        "section": "localnet"
      }
    },
    "testing": {
      "$ref": "file:model_testing.json#"
    },
    "features": {
      "$ref": "file:model_features.json#"
    },
    "notifs": {
      "$ref": "model_notifs.json",
      "$presentation": {
        "section": "notifs"
      }
    },
    "pointset": {
      "$ref": "file:model_pointset.json#",
      "$presentation": {
        "section": "pointset"
      }
    },
    "structure": {
      "existingJavaType": "java.util.HashMap<String, DiscoveryEvents>",
      "patternProperties": {
        "^[a-z][a-z0-9]*(_[a-z0-9]+)*$": {
          "$ref": "file:events_discovery.json"
        }
      }
    },
    "policy": {
      "$ref": "file:model_policy.json#"
  }
  }
}

=== grafnu/udmi/tests/sites/basic/devices/SNS-4/expected/metadata_norm.json
{
  "externals": {
    "dbo": {
      "ext_id": "0060917f-8c21-47c4-b011-52521085fdc3",
      "label": "VAV CO 1-2-37",
      "type": "HVAC/VAV_SD_DSP"
    },
    "ifc": {
      "etag": "98bac980",
      "ext_id": "a87a9b4b-e9e5-424b-9a4e-22378987dddd",
      "type": "IfcDoor"
    },
    "json_ld": {
      "ext_id": "https://dbpedia.org/page/John_Lennon",
      "type": "person"
    }
  },
  "gateway": {
    "gateway_id": "GAT-123",
    "target": {
      "addr": "2",
      "family": "modbus",
      "network_id": "modbus_rtu_1"
    }
  },
  "pointset": {
    "exclude_points_from_config": true,
    "points": {
      "fan_status": {
        "ref": "1/101?type=BOOLEAN"
      },
      "filter_differential_pressure": {
        "ref": "4/30005?type=UINT32&worder=LWF&scale=0.01",
        "units": "Pascals"
      },
      "split_threshold": {
        "units": "Imperial-gallons-per-minute"
      },
      "triangulating_axis": {
        "units": "Degrees-phase"
      }
    },
    "sample_rate_sec": 30
  },
  "system": {
    "location": {
      "section": "2-3N8C",
      "site": "ZZ-TRI-FECTA"
    },
    "min_loglevel": 300,
    "physical_tag": {
      "asset": {
        "guid": "drw://TBA",
        "name": "SNS-4",
        "site": "ZZ-TRI-FECTA"
      }
    }
  },
  "timestamp": "2020-05-01T13:39:07Z",
  "version": "1.5.2"
}

=== grafnu/udmi/tests/sites/basic/devices/GAT-123/metadata.json
{
  "pointset": {
    "points": {
      "globulating_globar": {
        "units": "Bars"
      }
    }
  },
  "system": {
    "node_type": "cloud_gateway",
    "location": {
      "section": "2-3N8C"
    },
    "physical_tag": {
      "asset": {
        "guid": "drw://TBB",
        "site": "ZZ-TRI-FECTA",
        "name": "GAT-123"
      }
    }
  },
  "gateway": {
  },
  "localnet": {
    "families": {
      "vendor": {
        "addr": "20231"
      }
    },
    "networks": {
      "modbus_rtu_1": {
        "family": "modbus",
        "adjunct": {
          "protocol": "RTU",
          "baud": 9600,
          "parity": "none",
          "data_bits": 8,
          "stop_bits": 1,
          "device": "COM1"
        }
      }
    }
  },
  "cloud": {
    "auth_type": "ES256",
    "connection_type": "GATEWAY"
  },
  "version": "1.5.2",
  "timestamp": "2020-05-01T13:39:07Z"

}

=== grafnu/udmi/tests/sites/basic/devices/GAT-123/expected/metadata_norm.json
{
  "cloud": {
    "auth_type": "ES256",
    "resource_type": "GATEWAY"
  },
  "gateway": {
    "proxy_ids": [
      "AHU-22",
      "SNS-4",
      "SNS-8"
    ]
  },
  "localnet": {
    "families": {
      "vendor": {
        "addr": "20231"
      }
    },
    "networks": {
      "modbus_rtu_1": {
        "adjunct": {
          "baud": "9600",
          "data_bits": "8",
          "device": "COM1",
          "parity": "none",
          "protocol": "RTU",
          "stop_bits": "1"
        },
        "family": "modbus"
      }
    }
  },
  "pointset": {
    "points": {
      "globulating_globar": {
        "units": "Bars"
      }
    },
    "sample_rate_sec": 30
  },
  "system": {
    "location": {
      "section": "2-3N8C",
      "site": "ZZ-TRI-FECTA"
    },
    "min_loglevel": 300,
    "node_type": "cloud_gateway",
    "physical_tag": {
      "asset": {
        "guid": "drw://TBB",
        "name": "GAT-123",
        "site": "ZZ-TRI-FECTA"
      }
    }
  },
  "timestamp": "2020-05-01T13:39:07Z",
  "upgraded_from": "1.5.2",
  "version": "1.5.3"
}

=== grafnu/udmi/tests/sites/basic/devices/SNS-4/metadata.json
{
  "pointset": {
    "exclude_points_from_config": true,
    "points": {
      "triangulating_axis": {
        "units": "Degrees-phase"
      },
      "split_threshold": {
        "units": "Imperial-gallons-per-minute"
      },
      "fan_status": {
        "ref": "1/101?type=BOOLEAN"
      },
      "filter_differential_pressure": {
        "units": "Pascals",
        "ref": "4/30005?type=UINT32&worder=LWF&scale=0.01"
      }
    }
  },
  "system": {
    "location": {
      "section": "2-3N8C"
    },
    "physical_tag": {
      "asset": {
        "guid": "drw://TBA",
        "site": "ZZ-TRI-FECTA",
        "name": "SNS-4"
      }
    }
  },
  "externals": {
    "dbo": {
      "ext_id": "0060917f-8c21-47c4-b011-52521085fdc3",
      "type": "HVAC/VAV_SD_DSP",
      "label": "VAV CO 1-2-37"
    },
    "ifc": {
      "ext_id": "a87a9b4b-e9e5-424b-9a4e-22378987dddd",
      "etag": "98bac980",
      "type": "IfcDoor"
    },
    "json_ld": {
      "ext_id": "https://dbpedia.org/page/John_Lennon",
      "type": "person"
    }
  },
  "gateway": {
    "gateway_id": "GAT-123",
    "target": {
      "family": "modbus",
      "addr": "2",
      "network_id": "modbus_rtu_1"
    }
  },
  "version": "1.5.2",
  "timestamp": "2020-05-01T13:39:07Z"
}
